name: Validate Pull Requests
on:
  - pull_request

jobs:
  quality_checks:
    name: Run Quality Checks
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout feature branch
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
      - name: Install packages
        run: npm i

      - name: Run the Expo Doctor checks
        run: npx expo-doctor

      - name: Check the typescript is valid
        run: npm run validate:type-check

      - name: Lint the code
        run: npm run lint

      - name: Run the unit tests
        run: npm run validate:test
