on:
  - pull_request

jobs:
  quality_checks:
    name: Run Quality Checks
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: Run the unit tests
        run: npm test
        with:
          cmd: test
